name: liberated-chat
version: ${version}
description: "Probably the simplest minecraft plugin that disables chat reporting."
authors: ["Wojciech Paruch <teamaster69@proton.me>", "Timongcraft"]
website: "https://modrinth.com/plugin/liberated-chat"

api-version: 1.21
main: com.blay.liberatedchat.LiberatedChat
